### ISSUE TITLE
VirtualBox i can do nothing.

### ISSUE THREAD

**Issue by alexohneander** [install-logos/logos#34]
I boot the Logos on a VirtualBox.
All fine!
When i'm on the i3 i cannot do anything.
? 

I use a Macbook Pro, is the Keyboard a Problem( $mod + Enter )?

**Comment by Luminarys** [comment]
I'll assume you've figured it out yourself, but just in case the $mod key should be the apple key with the four ringed clover like symbol on it. $mod + Enter will open urxvt, $mod + d will open dmenu(app launcher). In addition, you can move windows around by holding $mod and left clicking and resize windows with $mod and right clicking.
